using CustomVP;
using System.Collections.Generic;

public static class Suspensions
{
	public static List<SuspensionPart> suspensions;

	public static List<SuspensionUpgrade> suspensionUpgrades;

	public static List<WheelsUpgrade> wheelsUpgrades;

	static Suspensions()
	{
		suspensions = new List<SuspensionPart>();
		suspensionUpgrades = new List<SuspensionUpgrade>();
		wheelsUpgrades = new List<WheelsUpgrade>();
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DEFAULT", "DEFAULT", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "SolidAxleFrontSuspension", "Solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "AssetFrontSuspension", "Solid axle PRO", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "IndependentFrontSuspension", "Independent type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "IBeamFrontSuspension", "I-Beam type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "TrophyFrontSuspension", "Trophy type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "FordAFrontSuspension", "Trophy type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler2SolidAxleFrontSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler5SolidAxleFrontSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "CrawlerSolidAxleFrontSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler3SolidAxleFrontSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler4SolidAxleFrontSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DragATVFrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "PolarisUTVFrontSuspension", "UTV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "YamahaATVFrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "YFZ1000RUTVFrontSuspension", "UTV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV4FrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV5FrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV1FrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV2FrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV3FrontSuspension", "ATV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DirtBikeFrontSuspension", "Dirt bike suspension", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "SolidAxleRearSuspension", "Solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DoubleSolidAxleRearSuspension", "Double solid axle", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "TrophyRearSuspension", "Trophy type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "AssetRearSuspension", "Solid axle PRO", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler2SolidAxleRearSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler5SolidAxleRearSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "CrawlerSolidAxleRearSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler3SolidAxleRearSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler4SolidAxleRearSuspension", "Crawler solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler3TrophyRearSuspension", "Trophy type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "Crawler4TrophyRearSuspension", "Trophy type", "Suspension description", 5000));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DragATVRearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "PolarisUTVRearSuspension", "UTV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "YamahaATVRearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "YFZ1000UTVRearSuspension", "UTV independent type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV4RearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV5RearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV1RearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV2RearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "ATV3RearSuspension", "ATV solid axle type", "Suspension description", 0));
		suspensions.Add(new SuspensionPart(VehicleType.Any, "DirtBikeRearSuspension", "Dirt bike suspension", "Suspension description", 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IBeamFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("IBeamFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IBeamFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IBeamFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IBeamFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IndependentFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("IndependentFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IndependentFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IndependentFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("IndependentFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("SolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DoubleSolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("DoubleSolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DoubleSolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DoubleSolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DoubleSolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("TrophyRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("FordAFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("FordAFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("FordAFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("FordAFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("FordAFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("AssetRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler2SolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3SolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4SolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler5SolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4TrophyRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4TrophyRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4TrophyRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4TrophyRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler4TrophyRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3TrophyRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3TrophyRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3TrophyRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3TrophyRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("Crawler3TrophyRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("CrawlerSolidAxleRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DragATVRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("PolarisUTVRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YamahaATVRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000RUTVFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000RUTVFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000RUTVFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000RUTVFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000RUTVFrontSuspension", 4, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000UTVRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000UTVRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000UTVRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000UTVRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("YFZ1000UTVRearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4FrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4FrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4FrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4FrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4FrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4RearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4RearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4RearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4RearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV4RearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5FrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5FrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5FrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5FrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5FrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5RearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5RearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5RearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5RearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV5RearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1FrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1FrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1FrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1FrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1FrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1RearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1RearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1RearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1RearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV1RearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2FrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2FrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2FrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2FrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2FrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2RearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2RearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2RearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2RearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV2RearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3FrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3FrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3FrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3FrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3FrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3RearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3RearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3RearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3RearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("ATV3RearSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeFrontSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeFrontSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeFrontSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeFrontSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeFrontSuspension", 4, 3000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeRearSuspension", 0, 0));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeRearSuspension", 1, 1000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeRearSuspension", 2, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeRearSuspension", 3, 2000));
		suspensionUpgrades.Add(new SuspensionUpgrade("DirtBikeRearSuspension", 4, 3000));
		wheelsUpgrades.Add(new WheelsUpgrade(0, 0));
		wheelsUpgrades.Add(new WheelsUpgrade(1, 1000));
		wheelsUpgrades.Add(new WheelsUpgrade(2, 2000));
		wheelsUpgrades.Add(new WheelsUpgrade(3, 3000));
		wheelsUpgrades.Add(new WheelsUpgrade(4, 4000));
	}

	public static SuspensionPart GetSuspension(VehicleType _vehicleType, string suspensionName)
	{
		SuspensionPart suspensionPart = suspensions.Find((SuspensionPart s) => s.vehicleType == _vehicleType && s.partName == suspensionName);
		if (suspensionPart == null)
		{
			suspensionPart = suspensions.Find((SuspensionPart s) => s.vehicleType == VehicleType.Any && s.partName == suspensionName);
		}
		return suspensionPart;
	}

	public static SuspensionUpgrade GetSuspensionUpgrade(string suspensionName, int stage)
	{
		return suspensionUpgrades.Find((SuspensionUpgrade u) => u.SuspensionName == suspensionName && u.Stage == stage);
	}

	public static WheelsUpgrade GetWheelsUpgrade(int stage)
	{
		return wheelsUpgrades.Find((WheelsUpgrade u) => u.Stage == stage);
	}
}
